name: akash-wf2

on: 
  workflow_dispatch:

jobs:
  second_job:
    runs-on: self-hosted
  
  steps:
  - uses: actions/checkout@v3

  - name: trying to create second workflow
    run: echo Second workflow teyar krr rhe h

  

  